### ISSUE TITLE
HW1: function compress missing an input 

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#2]
I'm not sure I understand how python deals with scope, but shouldn't compress take both the matrix and a number n as inputs, not just n?

**Comment by jmbejara** [comment]
I think a good description of how scoping works with a nice mnemonic can be found here: https://stackoverflow.com/questions/291978/short-description-of-the-scoping-rules 

With regards to *style*, if I were writing software, it would be better to write the `compress` function so that it takes the matrices as arguments. Since I'm just writing a short, one-off script here, it's more convenient (in my opinion) to write it the way that I did.

There can be some gotcha's when it comes to scoping---enough so that I thought it would be fun to write down a few examples in a Jupyter notebook. You can check it out here: https://github.com/jmbejara/comp-econ-sp18/blob/master/misc/scoping_rules.ipynb

If you, or anyone else, has any interesting examples to add to this notebook, feel free to suggest or discuss them here.
