### ISSUE TITLE
HW4 some numbers slightly off compared to sample output

### ISSUE THREAD

**Issue by vuphan95** [jmbejara/comp-econ-sp18#35]
![screenshot 89](https://user-images.githubusercontent.com/37914368/39402656-ef2b53b4-4b2a-11e8-9f87-00410401f843.png)
As shown in the screenshot, the numbers I got are slightly off compared to the sample output. What confuses me is the fact that my median wage column is correct but the other two columns are not. I would appreciate some hint to help me look for where and what I did wrong. Thank you very much!

**Comment by jmbejara** [comment]
Interesting. It's strange to me that you would be getting the same answers on the median but not on the mean. I'm using `np.average`. I get the same answer when I use `weightedstats.numpy_weighted_mean`. Immediately after I run the code to compute these series, this is what my instance of `df` looks like:

![image](https://user-images.githubusercontent.com/3770323/39403039-e29bc506-4b35-11e8-884e-eb9d6b889c11.png)

**Comment by tyler-patterson** [comment]
I had this exact same issue and it turned out that this happens if you drop NA values AFTER dropping extraneous columns in Q6.  If you drop NA values BEFORE getting rid of the columns, you should get the numbers that show up in the sample output.

The question seems to be asking you to drop columns first, leading to the "wrong" values, so rewording the question might make sense.

**Comment by jmbejara** [comment]
I've updated the HW (see 0fa49a59b7718e1f2308134b87630b7f82355cab) to add this clarification. Thanks for solving this!

**Comment by wilson97** [comment]
@vuphan95 did the fix work for you? I have the same issue but reordering the NA drop doesn't help for me.

**Comment by vuphan95** [comment]
@wilson97 I went from having many numbers off to having only one or two values different from the sample output.
