### ISSUE TITLE
Issues Finding Variables for IPUMS Data Download

### ISSUE THREAD

**Issue by benpicker** [jmbejara/comp-econ-sp18#37]
I'm running into a couple issues while trying to download the data. 

1. When I try to add YEAR and ASECWT to the cart, they don't go in the cart. Why? 
2. I cannot find HRSWORKLY in the IPUMS database. Any idea why?

**Comment by afgong** [comment]
1. YEAR is preselected, so it'll show up after you add the samples into your cart. I had the same issue. Also, are you using IPUMS CPS data? If so, ASECWT should show up; you might be in the general IPUMS database currently, which is why you can't find ASECWT.

2. I believe it's UHRSWORKLY not HRSWORKLY

**Comment by benpicker** [comment]
Re 1: ASECWT comes up, but I cannot add it. It behaves like YEAR.
Re 2: Great! that was super helpful.

**Comment by benpicker** [comment]
Also, which samples do I need? 

ASEC
Basic Monthly

Which ones from these do I need?

**Comment by jmbejara** [comment]
Only use the ASEC samples. Do not include the basic monthly.
