### ISSUE TITLE
Are we allowed to have negative weights in our portfolio optimization?

### ISSUE THREAD

**Issue by NihilistOkapi** [jmbejara/comp-econ-sp18#4]
I do not see anything specific about non negative weights in our portfolio optimization. Is that allowed?

**Comment by jmbejara** [comment]
Hi. Yeah, negative weights are allowed here. The negative weights correspond to "shorting" a security (https://en.wikipedia.org/wiki/Short_(finance) ). I considered adding an additional part to the assignment that required the additional constraint that weights be non-negative, since it's an interesting exercise that people often use in this kind of analysis, but I didn't in the end. Also, as a side note, the case *without* the "no-short-sale" constraint can be solved analytically. The case with the constraint cannot and requires that we use an numerical optimizer like we are doing in the HW.
