### ISSUE TITLE
MLE Lecture

### ISSUE THREAD

**Issue by ethanmetzger** [jmbejara/comp-econ-sp18#45]
<img width="522" alt="screen shot 2018-05-05 at 7 01 46 pm" src="https://user-images.githubusercontent.com/37875239/39668581-125a0e5e-5097-11e8-872a-e20fcd3ef887.png">

I am having a problem opening the updated MLE Lecture. Any idea how to fix the error?

**Comment by jmbejara** [comment]
I believe that this error occurred because Git was trying to merge the new changes with changes that you made when you ran the original version of the notebook. [The Jupyter notebook format and Git don't always work very well together.](http://timstaley.co.uk/posts/making-git-and-jupyter-notebooks-play-nice/)

Here are a couple of solutions:

 - The easiest is to delete your copy of the notebook and download the new version. You will lose any of your own changes you made to the lecture notebook with this method.
 - A better way is to do something like. Depending on the state of you Git repo, you could "discard changes" in the MLE notebook and reset it to the current version of `master`. Note that you will still lose any of your own changes you made to the lecture notebook with this method. The following screenshot shows how to do this in GitKraken:

![discard_changes](https://user-images.githubusercontent.com/3770323/39669529-0bbb7ae8-50b4-11e8-8830-6e9d7e784c83.png)

 - An overkill solution would be something like [this](https://stackoverflow.com/a/1628334/1411791). With this solution, you will discard **all** changes that have been made in the repo directory and reset everything to match the current version that I have on GitHub. You can accomplish this in GitKraken by making sure that you are on the master branch and then right-clicking the most recent commit of the master branch. There is an option that says "reset master to this commit" and you can choose a "hard reset." I've included a screenshot:

![image](https://user-images.githubusercontent.com/3770323/39669564-e55c41ec-50b4-11e8-95ef-510d515fe86f.png)

Let me know if you would like additional clarification. Git can be tricky!!

**Comment by ethanmetzger** [comment]
I went with the 2nd option. Thanks for the help, Jeremy!
