### ISSUE TITLE
MLE Visualization Q3

### ISSUE THREAD

**Issue by alykhanb96** [jmbejara/comp-econ-sp18#47]
Been stuck on Q3 for a while. The error I get says that plt.plot cant take a generator.

def pdf(x):
  a = (1/(x*0.5 *(2*np.pi)**(1/2)))* math.exp(-1* ((math.log10(x) - 11)**2)/(2* (0.5**2)))
  return a
               
grid = np.linspace(0, 150000, num= 150000)

#fig, ax = plt.subplots(figsize=(10, 6))
#ax.hist(obs, bins=40, normed=True)
new = map(pdf, grid)
plt.plot(grid, new, 'k-', linewidth=2)
plt.show()

**Comment by jmbejara** [comment]
Hi Aly. Here are some suggestions:

  - Don't use `map`. Use vectorization using `numpy` as we discussed. (numpy's 'ufuncs')
  - Try simplifying the problem to understand the error. You'll see that `new` is a generator and not a list.

Compare 
```python
def pdf(x):
    a = x**2
    return a

grid = np.linspace(-5, 5, num= 20)
new = map(pdf, grid)
plt.plot(grid, new, 'k-', linewidth=2)
plt.show()
```
with
 ```python
def pdf(x):
    a = x**2
    return a

grid = np.linspace(-5, 5, num= 20)
new = list(map(pdf, grid))
plt.plot(grid, new, 'k-', linewidth=2)
plt.show()
```

After running `new = map(pdf, grid)`, you'll see this:

![image](https://user-images.githubusercontent.com/3770323/39730217-f30098e4-5225-11e8-9c32-a3a0d4b3c9af.png)


  - Don't use `math.exp` or `math.log`. Use `np.exp` and `np.log`. This will help you so that you don't have to use `map`.

Let me know if this helps!
