### ISSUE TITLE
Does TIRE enter into Variable profits?

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#60]
X=[W,Z] so I assume it does, but the formula you gave us for theta only includes four betas, and we already have 4 Z variables. Should we add a 5th beta?

**Comment by jmbejara** [comment]
It enters into V and F through the `N` argument. The sums are written as going from `n=2` to `n=N`. This could be rewritten with indicator functions. In my code, I write it as a sum across a vector of the alphas, ending at `N`.

**Comment by isabelalmazan** [comment]
In the model, which $\gamma$ does $\gamma_L$ correspond to in the $F_1 = \gamma_1 + \gamma_L W_L$ equation? Assuming each $W_L$ corresponds to each row L's land value, how does $\gamma_L$ relate to $W_L$? Is $W_L$ a different variable/ column in the data than W?

Edit: does the order of the economic variables in X matter? ie: could I just group the four columns of economic data into X in the order they come in the table (ELD, FFRAC, PINC, LNHDD)? Or should the order be FFRAC first because it's related to land, which is what W is?

Also what is the difference between Y and S? Are they both market size? Or is S market size and Y is just the amalgamation of the variables that help describe market size (ie: all of the lambdas)?

**Comment by jmbejara** [comment]
Hi @isabelalmazan . 

  - $\gamma_L$ is a scalar constant that is different from $\gamma_1$, $\gamma_2$, etc. 
  - For our purposes, $W_L$ will always be the same thing as $W$, which is just the "land value" variable.
  - In terms of writing the code, I have a vector `gamma` that I use to keep track of all of the $\gamma$ coefficients. The order the you use to store the different gammas in this vector shouldn't matter. It shouldn't matter as long as you're consistent---this applies to the any of the variables. In my code, I use `gamma[5]` to represent $\gamma_L$ and `gamma[0]` is $\gamma_1$, `gamma[1]` is $\gamma_2$, etc.

  - $gamma_L$ is the coefficient on the variable "land value" in determining the fixed cost $F$ that a potential entrant into the market faces.

  - Y represents a set of different demographic variables that might determine the size of a market, S. S is the size of the market. We could just let S be equal to the town population variable. However, in reality, the size of the market is not limited to the town population. The "effective size of the market", a better definition of S, should really take into account the population of surrounding areas, the number of commuters, etc. These extra variables are included in Y and are used to better estimate the effective market size, S. The lambdas are the coefficients on the demographic variables and are estimated. They tell us how variables like the number of commuters affect the effective size of the market. Think about equation (9) as a regression (even though it's not like a regression that you've seen before) where S is the left-hand side variable and the variables and coefficients on the right-hand side are things that try to explain S.
