### ISSUE TITLE
Intercept in Fixed Effects Models?

### ISSUE THREAD

**Issue by Jacob-Bishop** [jmbejara/comp-econ-sp18#65]
Should we include an  intercept in our formula when calculating the seatbelts regressions with year and/or state fixed effects? I wasn't sure, since it wasn't specified in the assignment.

**Comment by jmbejara** [comment]
Good question! For part (1), include an intercept. For (2) and (3), you technically can't add a constant. That is because when we are, for example, adding state fixed effects it means that were adding an intercept for each state. We can represent this as adding a dummy variable for each state. If we add an intercept, then we will end up in a "dummy variable trap" where are of our regressors are perfectly multicollinear.

Note, though, that the software will allow you to add an intercept to the fixed effects model. If you do this, you'll notice that this won't change the estimates. What it is doing, and I'm not sure of the exact details, is something like reporting the average of the fixed effects.
